// Code generated by "stringer -type=Rarity"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Rollback-1]
	_ = x[Rare-10]
	_ = x[Uncommon-90]
	_ = x[Common-400]
}

const (
	_Rarity_name_0 = "Rollback"
	_Rarity_name_1 = "Rare"
	_Rarity_name_2 = "Uncommon"
	_Rarity_name_3 = "Common"
)

func (i Rarity) String() string {
	switch {
	case i == 1:
		return _Rarity_name_0
	case i == 10:
		return _Rarity_name_1
	case i == 90:
		return _Rarity_name_2
	case i == 400:
		return _Rarity_name_3
	default:
		return "Rarity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
